apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:                        #A
- ../../base

patchesStrategicMerge:
- debug.yaml                  #B
- replica_count.yaml
  
images:                       #C
- name: gitopsbook/sample-app
  newTag: v0.2
